name: Build and Test 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build 
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 

    - name: Build
      run: dotnet build --configuration Release
  
    - name: Test
      run: dotnet test --configuration Release --logger "trx;LogFileName=testresults.trx" # Adjust for your test runner and output format
      continue-on-error: true # Continue running other steps even if tests fail

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '**/testresults.trx' # Adjust to match your test results file

  # Add more jobs as needed for deployment, additional testing, etc.
